import React from "react"

export default function Rarities({closeModal}) {
    return (
        <div className={"rarities-modal__container"}>
            <div className={"rarities-close__container"}>
                <button className={"rarities-close"} onClick={() => closeModal(false)}>X</button>
            </div>
            <h3>Rarity chart</h3>
            <div className={"rarities-modal"}>
                <div className={"rarities-table"}>
                    <table>
                        <thead className={"rarities-thead"}>
                        <tr>
                            <td>Attribute</td>
                            <td>% Chance</td>
                        </tr>
                        </thead>
                        <tr>
                            <td>Alien</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Arm_cannon</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Astronaut</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Candy</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Card</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Catrina</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Clam_and_Snorkel</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Cocktail</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Coin</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Contract</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Cool</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Cowboy</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Cultural</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Enlightened</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Fairies</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Fire_spirit</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Fired_chicken</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Golf_club</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Hero</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Jungle</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Kawaii</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Knife</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Lawyer</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Legendary</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Metal_skeleton</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Monke</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Ninja</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Oni</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Otaku</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Pig</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Pijama</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Pillow</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Samurai</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Schoolgirl</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Seal</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Shuriken</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Sombrero</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Space</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Spirit_master</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Sunscreen</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>The_Only_One</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Water</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Will_O'Wisp</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Wrestler</td>
                            <td>1%</td>
                        </tr>
                        <tr>
                            <td>Cellphone</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Keys</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Knight</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Lighter</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Manga</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Minion</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Monster</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Pendant</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Socks</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Soulless</td>
                            <td>2%</td>
                        </tr>
                        <tr>
                            <td>Bandages</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Bandana</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Beach</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Boots</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Evil</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Metal</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Onesie</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Swimming_shorts</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Sword</td>
                            <td>3%</td>
                        </tr>
                        <tr>
                            <td>Crocs</td>
                            <td>4%</td>
                        </tr>
                        <tr>
                            <td>Epic</td>
                            <td>4%</td>
                        </tr>
                        <tr>
                            <td>Fire</td>
                            <td>5%</td>
                        </tr>
                        <tr>
                            <td>Ghost</td>
                            <td>5%</td>
                        </tr>
                        <tr>
                            <td>Bowler_Hat</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Boxers</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Classy</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Floaties</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Glasses</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Head_Lamp</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Jeans</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Monsters</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Party_Bracelet</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Party_Clothes</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Party_Hardy</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Ragged_Shirt</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Regular_Shoes</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Swimming_Shorts</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Tennis</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Trick_or_Treat</td>
                            <td>7%</td>
                        </tr>
                        <tr>
                            <td>Gloves</td>
                            <td>9%</td>
                        </tr>
                        <tr>
                            <td>Cap</td>
                            <td>10%</td>
                        </tr>
                        <tr>
                            <td>Jacket</td>
                            <td>10%</td>
                        </tr>
                        <tr>
                            <td>Rare</td>
                            <td>10%</td>
                        </tr>
                        <tr>
                            <td>Shirt</td>
                            <td>11%</td>
                        </tr>
                        <tr>
                            <td>Barefoot</td>
                            <td>13%</td>
                        </tr>
                        <tr>
                            <td>Sandals</td>
                            <td>14%</td>
                        </tr>
                        <tr>
                            <td>Hoodie</td>
                            <td>17%</td>
                        </tr>
                        <tr>
                            <td>Casual</td>
                            <td>20%</td>
                        </tr>
                        <tr>
                            <td>Uncommon</td>
                            <td>25%</td>
                        </tr>
                        <tr>
                            <td>Common</td>
                            <td>60%</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    )
}